export const ERROR_CODES = {
  // 프론트 커스텀 에러
  LOGIN_REQUIRED: 'LOGIN_REQUIRED',
  NO_ACCESS_TOKEN: 'NO_ACCESS_TOKEN',
  NO_REFRESH_TOKEN: 'NO_REFRESH_TOKEN',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  TOKEN_REISSUE_FAILED: 'TOKEN_REISSUE_FAILED',
  NEXT_SERVER_ERROR: 'NEXT_SERVER_ERROR',
  REPLAY_REQUIRED: 'REPLAY_REQUIRED',
  LOGOUT_COMPLETED: 'LOGOUT_COMPLETED',

  // Auth 관련
  NOT_FOUND_TOKEN: 'NOT_FOUND_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  NOT_REFRESH_TOKEN: 'NOT_REFRESH_TOKEN',
  TOKEN_TYPE_NOT_MATCH: 'TOKEN_TYPE_NOT_MATCH',
  NOT_FOUND_MEMBER: 'NOT_FOUND_MEMBER',
  ALREADY_EXISTING_NICKNAME: 'ALREADY_EXISTING_NICKNAME',
  MEMBER_WITHDRAWAL_FAIL: 'MEMBER_WITHDRAWAL_FAIL',
  ALREADY_HAVE_RESUME: 'ALREADY_HAVE_RESUME',
  NOT_FOUND_OAUTH_PROVIDER: 'NOT_FOUND_OAUTH_PROVIDER',
  EXPIRED_ACCESS_TOKEN: 'EXPIRED_ACCESS_TOKEN',
  INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',

  // Resume 관련
  NOT_FOUND_RESUME: 'NOT_FOUND_RESUME',
  UNAUTHORIZED_ACCESS_RESUME: 'UNAUTHORIZED_ACCESS_RESUME',
  RESUME_NOT_FOUND_PLEASE_REGISTER: 'RESUME_NOT_FOUND_PLEASE_REGISTER',
  INVALID_RESUME_CONTENT: 'INVALID_RESUME_CONTENT',

  // TodoList 관련
  TODO_LIST_NOT_BELONG_TO_JD: 'TODO_LIST_NOT_BELONG_TO_JD',
  CATEGORY_REQUIRED: 'CATEGORY_REQUIRED',
  TODO_LIST_LIMIT_EXCEEDED_FOR_CATEGORY:
    'TODO_LIST_LIMIT_EXCEEDED_FOR_CATEGORY',
  INVALID_TODO_LIST_CATEGORY: 'INVALID_TODO_LIST_CATEGORY',
  UNAUTHORIZED_ACCESS_TODO: 'UNAUTHORIZED_ACCESS_TODO',

  // JD 관련
  FAILED_ANALYSIS_REQUEST: 'FAILED_ANALYSIS_REQUEST',
  FAILED_ANALYSIS_REQUEST_TEXT_LENGTH_EXCEED:
    'FAILED_ANALYSIS_REQUEST_TEXT_LENGTH_EXCEED',
  NOT_FOUND_JD: 'NOT_FOUND_JD',
  UNAUTHORIZED_ACCESS_JD: 'UNAUTHORIZED_ACCESS_JD',
  JD_LIMIT_EXCEEDED: 'JD_LIMIT_EXCEEDED',
  INVALID_JOB_NAME: 'INVALID_JOB_NAME',
  INVALID_JOB_DESCRIPTION_CONTENT: 'INVALID_JOB_DESCRIPTION_CONTENT',
  AI_ANALYSIS_UNAVAILABLE: 'AI_ANALYSIS_UNAVAILABLE',

  // API, 서버 오류
  INVALID_API_REQUEST: 'INVALID_API_REQUEST',
  API_SERVER_ERROR: 'API_SERVER_ERROR',
  FAILED_JSON_PROCESS: 'FAILED_JSON_PROCESS',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export const ERROR_MESSAGES = {
  // 프론트 커스텀 에러
  LOGIN_REQUIRED: '로그인이 필요합니다.',
  NO_ACCESS_TOKEN: '세션이 만료됐습니다. 다시 시도해 주세요.',
  NO_REFRESH_TOKEN: '로그인이 필요합니다.',
  INVALID_REFRESH_TOKEN: '로그인 정보가 만료됐습니다. 다시 로그인해 주세요.',
  TOKEN_REISSUE_FAILED: '세션을 복구하지 못했어요. 다시 로그인해 주세요.',
  NEXT_SERVER_ERROR:
    '일시적인 오류가 발생했습니다. 잠시 후 다시 시도해 주세요.',
  REPLAY_REQUIRED: '세션이 끊겼습니다. 다시 시도해 주세요.',
  LOGOUT_COMPLETED: '로그아웃 되었습니다.',

  // Auth 관련
  NOT_FOUND_TOKEN: '유효하지 않은 로그인 정보입니다. 다시 시도해 주세요.',
  TOKEN_EXPIRED: '로그인 정보가 만료되었습니다. 다시 로그인해 주세요.',
  NOT_REFRESH_TOKEN: '잘못된 로그인 요청입니다. 다시 로그인해 주세요.',
  TOKEN_TYPE_NOT_MATCH: '로그인 정보가 올바르지 않습니다. 다시 시도해 주세요.',
  NOT_FOUND_MEMBER: '해당 회원 정보를 찾을 수 없습니다.',
  ALREADY_EXISTING_NICKNAME: '이미 사용 중인 닉네임입니다.',
  MEMBER_WITHDRAWAL_FAIL:
    '회원 탈퇴에 실패했습니다. 잠시 후 다시 시도해 주세요.',
  ALREADY_HAVE_RESUME: '이미 등록된 이력서가 있습니다.',
  NOT_FOUND_OAUTH_PROVIDER: '잘못된 로그인 경로입니다. 다시 시도해 주세요.',
  EXPIRED_ACCESS_TOKEN:
    '외부 로그인 세션이 만료되었습니다. 다시 로그인해 주세요.',
  INVALID_ACCESS_TOKEN:
    '로그인 정보가 올바르지 않습니다. 다시 로그인해 주세요.',

  // Resume 관련
  NOT_FOUND_RESUME: '이력서를 찾을 수 없습니다.',
  UNAUTHORIZED_ACCESS_RESUME: '해당 이력서를 볼 수 있는 권한이 없습니다.',
  RESUME_NOT_FOUND_PLEASE_REGISTER: '이력서를 등록해 주세요.',
  INVALID_RESUME_CONTENT:
    '이력서 내용이 올바르지 않습니다. 다시 작성해 주세요.',

  // TodoList 관련
  TODO_LIST_NOT_BELONG_TO_JD: '잘못된 채용 공고에 연결된 할 일입니다.',
  CATEGORY_REQUIRED: '카테고리를 선택해 주세요.',
  TODO_LIST_LIMIT_EXCEEDED_FOR_CATEGORY:
    '카테고리별 최대 10개까지만 추가할 수 있습니다.',
  INVALID_TODO_LIST_CATEGORY: '잘못된 카테고리입니다.',
  UNAUTHORIZED_ACCESS_TODO: '해당 할 일을 수정할 권한이 없습니다.',

  // JD 관련
  FAILED_ANALYSIS_REQUEST: '분석에 실패했습니다. 다시 시도해 주세요.',
  FAILED_ANALYSIS_REQUEST_TEXT_LENGTH_EXCEED:
    '할 일 제목이 너무 깁니다. 짧게 입력해 주세요.',
  NOT_FOUND_JD: '채용 공고를 찾을 수 없습니다.',
  UNAUTHORIZED_ACCESS_JD: '해당 채용 공고를 볼 수 있는 권한이 없습니다.',
  JD_LIMIT_EXCEEDED: '채용 공고는 최대 20개까지만 등록할 수 있습니다.',
  INVALID_JOB_NAME: '직무 이름이 올바르지 않습니다.',
  INVALID_JOB_DESCRIPTION_CONTENT:
    '채용 공고 내용이 올바르지 않습니다. 다시 작성해 주세요.',
  AI_ANALYSIS_UNAVAILABLE:
    '분석할 수 없는 내용입니다. 이력서와 공고를 다시 확인해 주세요.',

  // API, 서버 오류
  INVALID_API_REQUEST: '잘못된 요청입니다.',
  API_SERVER_ERROR: '서버 오류가 발생했습니다. 잠시 후 다시 시도해 주세요.',
  FAILED_JSON_PROCESS: '데이터 처리 중 오류가 발생했습니다.',
  INTERNAL_SERVER_ERROR:
    '서버 내부 오류가 발생했습니다. 잠시 후 다시 시도해 주세요.',
} as const;
