import { StateCreator } from 'zustand';

import { JDDetail, JobDescription, TodoItem } from '@/types/jds';

export interface TourDummySlice {
  dummyJds: JobDescription[];
  setDummyJds: (jds: JobDescription[]) => void;
  updateDummyJd: (
    jobId: number,
    updatedFields: Partial<JobDescription>
  ) => void;
  dummyJdDetails: JDDetail[];
  updateDummyJdDetail: (
    jobId: number,
    updatedFields: Partial<JDDetail>
  ) => void;
  syncDummyJdAndJdDetail: (
    jobId: number,
    updatedFields: Partial<
      Pick<JobDescription, keyof JobDescription & keyof JDDetail>
    >
  ) => void;
  dummyCheckedTodoList: number[];
  setDummyCheckedTodoList: (checkedTodoList: number[]) => void;
  addDummyCheckedTodo: (todoId: number) => void;
  removeDummyCheckedTodo: (todoId: number) => void;
}

const now = () => new Date().toISOString();
function getPastDate(daysAgo: number): string {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString();
}

function randInt(min: number, max: number) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

const CONTENT_SENTENCES = [
  '최근 프로젝트에서 맡은 역할과 주요 결과를 간단히 정리합니다.',
  '해당 작업에서 사용한 기술 스택과 적용한 아키텍처를 서술합니다.',
  '문제 해결 과정과 그로 인한 개선 효과를 수치로 표현해 보세요.',
  '팀 내에서 맡았던 책임과 협업 방식에 대해 기술합니다.',
  '관련 문서나 레퍼런스 링크가 있다면 해당 위치를 명시하세요.',
  '해당 경험이 지원 직무에 어떻게 연관되는지 연결해 설명합니다.',
  '실제 적용한 성능 최적화 사례나 테스트 전략을 덧붙입니다.',
  '프로젝트 진행 중 마주쳤던 주요 이슈와 대처 방안을 기술합니다.',
  '사용자 관점에서 얻은 인사이트와 개선 포인트를 기록하세요.',
  '결과적으로 얻은 교훈이나 다음에 개선할 점을 간단히 적습니다.',
];

function makeRandomContent(seedTitle?: string) {
  const lines = randInt(3, 7);
  const sentences: string[] = [];
  for (let i = 0; i < lines; i++) {
    const base =
      CONTENT_SENTENCES[Math.floor(Math.random() * CONTENT_SENTENCES.length)];
    sentences.push(base);
  }
  return sentences.join(' ');
}

const dummyJobDescriptions: JobDescription[] = [
  {
    jd_id: 0,
    title: 'Frontend Engineer',
    bookmark: false,
    alarmOn: true,
    companyName: 'Codex Labs',
    totalPieces: 6,
    completedPieces: 1,
    applyAt: null,
    endedAt: getPastDate(-10),
    createdAt: getPastDate(20),
    updatedAt: getPastDate(19),
  },
  {
    jd_id: 1,
    title: 'Backend Developer',
    bookmark: true,
    alarmOn: false,
    companyName: 'HyungJPA Corp',
    totalPieces: 6,
    completedPieces: 3,
    applyAt: null,
    endedAt: '',
    createdAt: getPastDate(18),
    updatedAt: getPastDate(17),
  },
  {
    jd_id: 2,
    title: 'Product Designer',
    bookmark: false,
    alarmOn: false,
    companyName: 'Jogak Jogak Studio',
    totalPieces: 6,
    completedPieces: 0,
    applyAt: null,
    endedAt: getPastDate(-7),
    createdAt: getPastDate(16),
    updatedAt: getPastDate(15),
  },
  {
    jd_id: 3,
    title: 'UX Designer',
    bookmark: true,
    alarmOn: true,
    companyName: 'Flow UX Studio',
    totalPieces: 6,
    completedPieces: 2,
    applyAt: null,
    endedAt: getPastDate(-0.5),
    createdAt: getPastDate(14),
    updatedAt: getPastDate(13),
  },
  {
    jd_id: 4,
    title: 'Product Manager',
    bookmark: false,
    alarmOn: true,
    companyName: 'SprintWave',
    totalPieces: 6,
    completedPieces: 4,
    applyAt: null,
    endedAt: getPastDate(5),
    createdAt: getPastDate(12),
    updatedAt: getPastDate(11),
  },
  {
    jd_id: 5,
    title: 'Visual Designer',
    bookmark: false,
    alarmOn: false,
    companyName: 'Canvas Collective',
    totalPieces: 6,
    completedPieces: 6,
    applyAt: getPastDate(3),
    endedAt: getPastDate(2),
    createdAt: getPastDate(10),
    updatedAt: getPastDate(9),
  },
];

export const dummyTodoLists: Record<number, TodoItem[]> = {
  1: [
    {
      checklist_id: 1001,
      category: 'STRUCTURAL_COMPLEMENT_PLAN',
      title: '프로젝트 구조 정리',
      content: makeRandomContent('프로젝트 구조 정리'),
      memo: '',
      jdId: 0,
      createdAt: now(),
      updatedAt: now(),
      done: false,
    },
    {
      checklist_id: 1002,
      category: 'CONTENT_EMPHASIS_REORGANIZATION_PROPOSAL',
      title: '주요 성과 강조',
      content: makeRandomContent('주요 성과 강조'),
      memo: '',
      jdId: 0,
      createdAt: now(),
      updatedAt: now(),
      done: true,
    },
    {
      checklist_id: 1003,
      category: 'SCHEDULE_MISC_ERROR',
      title: '지원 일정 확인',
      content: makeRandomContent('지원 일정 확인'),
      memo: '',
      jdId: 0,
      createdAt: now(),
      updatedAt: now(),
      done: false,
    },
    {
      checklist_id: 1004,
      category: 'CONTENT_EMPHASIS_REORGANIZATION_PROPOSAL',
      title: '포트폴리오 링크 업데이트',
      content: makeRandomContent('포트폴리오 링크 업데이트'),
      memo: '',
      jdId: 0,
      createdAt: now(),
      updatedAt: now(),
      done: false,
    },
    {
      checklist_id: 1005,
      category: 'STRUCTURAL_COMPLEMENT_PLAN',
      title: '컴포넌트 재사용성 개선',
      content: makeRandomContent('컴포넌트 재사용성 개선'),
      memo: '',
      jdId: 0,
      createdAt: now(),
      updatedAt: now(),
      done: false,
    },
    {
      checklist_id: 1006,
      category: 'SCHEDULE_MISC_ERROR',
      title: '레퍼런스 메일 발송',
      content: makeRandomContent('레퍼런스 메일 발송'),
      memo: '',
      jdId: 0,
      createdAt: now(),
      updatedAt: now(),
      done: false,
    },
    {
      checklist_id: 1007,
      category: 'STRUCTURAL_COMPLEMENT_PLAN',
      title: '코드 리팩토링 완료',
      content: makeRandomContent('코드 리팩토링 완료'),
      memo: '',
      jdId: 0,
      createdAt: now(),
      updatedAt: now(),
      done: false,
    },
  ],
  2: [
    {
      checklist_id: 2001,
      category: 'STRUCTURAL_COMPLEMENT_PLAN',
      title: 'API 설계 문서화',
      content: makeRandomContent('API 설계 문서화'),
      memo: '',
      jdId: 1,
      createdAt: now(),
      updatedAt: now(),
      done: true,
    },
    {
      checklist_id: 2002,
      category: 'CONTENT_EMPHASIS_REORGANIZATION_PROPOSAL',
      title: '성능 개선 사례 정리',
      content: makeRandomContent('성능 개선 사례 정리'),
      memo: '',
      jdId: 1,
      createdAt: now(),
      updatedAt: now(),
      done: true,
    },
    {
      checklist_id: 2003,
      category: 'SCHEDULE_MISC_ERROR',
      title: '테스트 커버리지 보강',
      content: makeRandomContent('테스트 커버리지 보강'),
      memo: '',
      jdId: 1,
      createdAt: now(),
      updatedAt: now(),
      done: false,
    },
    {
      checklist_id: 2004,
      category: 'STRUCTURAL_COMPLEMENT_PLAN',
      title: '마이크로서비스 연동 점검',
      content: makeRandomContent('마이크로서비스 연동 점검'),
      memo: '',
      jdId: 1,
      createdAt: now(),
      updatedAt: now(),
      done: true,
    },
    {
      checklist_id: 2005,
      category: 'CONTENT_EMPHASIS_REORGANIZATION_PROPOSAL',
      title: '데이터베이스 스키마 개선',
      content: makeRandomContent('데이터베이스 스키마 개선'),
      memo: '',
      jdId: 1,
      createdAt: now(),
      updatedAt: now(),
      done: false,
    },
    {
      checklist_id: 2006,
      category: 'SCHEDULE_MISC_ERROR',
      title: '배포 파이프라인 확인',
      content: makeRandomContent('배포 파이프라인 확인'),
      memo: '',
      jdId: 1,
      createdAt: now(),
      updatedAt: now(),
      done: false,
    },
  ],
  3: [
    {
      checklist_id: 3001,
      category: 'CONTENT_EMPHASIS_REORGANIZATION_PROPOSAL',
      title: '포트폴리오 사례 재정리',
      content: makeRandomContent('포트폴리오 사례 재정리'),
      memo: '',
      jdId: 2,
      createdAt: now(),
      updatedAt: now(),
      done: false,
    },
    {
      checklist_id: 3002,
      category: 'STRUCTURAL_COMPLEMENT_PLAN',
      title: '디자인 시스템 보강',
      content: makeRandomContent('디자인 시스템 보강'),
      memo: '',
      jdId: 2,
      createdAt: now(),
      updatedAt: now(),
      done: false,
    },
    {
      checklist_id: 3003,
      category: 'SCHEDULE_MISC_ERROR',
      title: '면접 포트폴리오 준비',
      content: makeRandomContent('면접 포트폴리오 준비'),
      memo: '',
      jdId: 2,
      createdAt: now(),
      updatedAt: now(),
      done: false,
    },
    {
      checklist_id: 3004,
      category: 'CONTENT_EMPHASIS_REORGANIZATION_PROPOSAL',
      title: '사용자 리서치 결과 정리',
      content: makeRandomContent('사용자 리서치 결과 정리'),
      memo: '',
      jdId: 2,
      createdAt: now(),
      updatedAt: now(),
      done: false,
    },
    {
      checklist_id: 3005,
      category: 'STRUCTURAL_COMPLEMENT_PLAN',
      title: '프로토타입 제작',
      content: makeRandomContent('프로토타입 제작'),
      memo: '',
      jdId: 2,
      createdAt: now(),
      updatedAt: now(),
      done: false,
    },
    {
      checklist_id: 3006,
      category: 'SCHEDULE_MISC_ERROR',
      title: '레퍼런스 수집',
      content: makeRandomContent('레퍼런스 수집'),
      memo: '',
      jdId: 2,
      createdAt: now(),
      updatedAt: now(),
      done: false,
    },
  ],
  4: [
    {
      checklist_id: 4001,
      category: 'STRUCTURAL_COMPLEMENT_PLAN',
      title: '사용성 테스트 계획 수립',
      content: makeRandomContent('사용성 테스트 계획 수립'),
      memo: '',
      jdId: 3,
      createdAt: now(),
      updatedAt: now(),
      done: true,
    },
    {
      checklist_id: 4002,
      category: 'CONTENT_EMPHASIS_REORGANIZATION_PROPOSAL',
      title: '페르소나 재정의',
      content: makeRandomContent('페르소나 재정의'),
      memo: '',
      jdId: 3,
      createdAt: now(),
      updatedAt: now(),
      done: false,
    },
    {
      checklist_id: 4003,
      category: 'SCHEDULE_MISC_ERROR',
      title: '디자인 검토 회의 일정',
      content: makeRandomContent('디자인 검토 회의 일정'),
      memo: '',
      jdId: 3,
      createdAt: now(),
      updatedAt: now(),
      done: true,
    },
    {
      checklist_id: 4004,
      category: 'STRUCTURAL_COMPLEMENT_PLAN',
      title: '인터랙션 개선안 정리',
      content: makeRandomContent('인터랙션 개선안 정리'),
      memo: '',
      jdId: 3,
      createdAt: now(),
      updatedAt: now(),
      done: false,
    },
    {
      checklist_id: 4005,
      category: 'CONTENT_EMPHASIS_REORGANIZATION_PROPOSAL',
      title: '포트폴리오 사례 보강',
      content: makeRandomContent('포트폴리오 사례 보강'),
      memo: '',
      jdId: 3,
      createdAt: now(),
      updatedAt: now(),
      done: false,
    },
    {
      checklist_id: 4006,
      category: 'SCHEDULE_MISC_ERROR',
      title: '유관부서 피드백 수집',
      content: makeRandomContent('유관부서 피드백 수집'),
      memo: '',
      jdId: 3,
      createdAt: now(),
      updatedAt: now(),
      done: false,
    },
  ],
  5: [
    {
      checklist_id: 5001,
      category: 'CONTENT_EMPHASIS_REORGANIZATION_PROPOSAL',
      title: '직무 설명서 리뷰',
      content: makeRandomContent('직무 설명서 리뷰'),
      memo: '',
      jdId: 4,
      createdAt: now(),
      updatedAt: now(),
      done: false,
    },
    {
      checklist_id: 5002,
      category: 'STRUCTURAL_COMPLEMENT_PLAN',
      title: '로드맵 사례 정리',
      content: makeRandomContent('로드맵 사례 정리'),
      memo: '',
      jdId: 4,
      createdAt: now(),
      updatedAt: now(),
      done: true,
    },
    {
      checklist_id: 5003,
      category: 'SCHEDULE_MISC_ERROR',
      title: '팀 구성 이해',
      content: makeRandomContent('팀 구성 이해'),
      memo: '',
      jdId: 4,
      createdAt: now(),
      updatedAt: now(),
      done: true,
    },
    {
      checklist_id: 5004,
      category: 'CONTENT_EMPHASIS_REORGANIZATION_PROPOSAL',
      title: '성과 지표 정리',
      content: makeRandomContent('성과 지표 정리'),
      memo: '',
      jdId: 4,
      createdAt: now(),
      updatedAt: now(),
      done: true,
    },
    {
      checklist_id: 5005,
      category: 'STRUCTURAL_COMPLEMENT_PLAN',
      title: '케이스 스터디 준비',
      content: makeRandomContent('케이스 스터디 준비'),
      memo: '',
      jdId: 4,
      createdAt: now(),
      updatedAt: now(),
      done: false,
    },
    {
      checklist_id: 5006,
      category: 'SCHEDULE_MISC_ERROR',
      title: '레퍼런스 연락',
      content: makeRandomContent('레퍼런스 연락'),
      memo: '',
      jdId: 4,
      createdAt: now(),
      updatedAt: now(),
      done: true,
    },
  ],
  6: [
    {
      checklist_id: 6001,
      category: 'CONTENT_EMPHASIS_REORGANIZATION_PROPOSAL',
      title: '이미지 최적화',
      content: makeRandomContent('이미지 최적화'),
      memo: '',
      jdId: 5,
      createdAt: now(),
      updatedAt: now(),
      done: true,
    },
    {
      checklist_id: 6002,
      category: 'STRUCTURAL_COMPLEMENT_PLAN',
      title: '비주얼 시스템 정리',
      content: makeRandomContent('비주얼 시스템 정리'),
      memo: '',
      jdId: 5,
      createdAt: now(),
      updatedAt: now(),
      done: true,
    },
    {
      checklist_id: 6003,
      category: 'CONTENT_EMPHASIS_REORGANIZATION_PROPOSAL',
      title: '작업물 설명 보강',
      content: makeRandomContent('작업물 설명 보강'),
      memo: '',
      jdId: 5,
      createdAt: now(),
      updatedAt: now(),
      done: true,
    },
    {
      checklist_id: 6004,
      category: 'SCHEDULE_MISC_ERROR',
      title: '포트폴리오 호스팅 점검',
      content: makeRandomContent('포트폴리오 호스팅 점검'),
      memo: '',
      jdId: 5,
      createdAt: now(),
      updatedAt: now(),
      done: true,
    },
    {
      checklist_id: 6005,
      category: 'PORTFOLIO',
      title: '케이스 스터디 작성',
      content: makeRandomContent('케이스 스터디 작성'),
      memo: '',
      jdId: 5,
      createdAt: now(),
      updatedAt: now(),
      done: true,
    },
    {
      checklist_id: 6006,
      category: 'SCHEDULE_MISC_ERROR',
      title: '네트워크 연락',
      content: makeRandomContent('네트워크 연락'),
      memo: '',
      jdId: 5,
      createdAt: now(),
      updatedAt: now(),
      done: true,
    },
  ],
};

export const dummyJdDetails: JDDetail[] = [
  {
    jd_id: 0,
    title: 'Frontend Engineer',
    bookmark: false,
    companyName: 'Codex Labs',
    job: 'Frontend',
    content: 'React/Next.js 기반 프론트엔드 개발자',
    jdUrl: 'https://jogakjogak.com',
    memo: '',
    memberId: 101,
    alarmOn: true,
    applyAt: null,
    endedAt: getPastDate(-10),
    createdAt: getPastDate(20),
    updatedAt: getPastDate(19),
    totalPieces: 6,
    completedPieces: 1,
    toDoLists: dummyTodoLists[1],
  },
  {
    jd_id: 1,
    title: 'Backend Developer',
    bookmark: true,
    companyName: 'HyungJPA Corp',
    job: 'Backend',
    content: 'Node.js 기반 백엔드 개발자',
    jdUrl: 'https://jogakjogak.com/jd/2',
    memo: '레거시 시스템과의 연동 필요',
    memberId: 102,
    alarmOn: false,
    applyAt: null,
    endedAt: '',
    createdAt: getPastDate(18),
    updatedAt: getPastDate(17),
    totalPieces: 6,
    completedPieces: 3,
    toDoLists: dummyTodoLists[2],
  },
  {
    jd_id: 2,
    title: 'Product Designer',
    bookmark: false,
    companyName: 'Jogak Jogak Studio',
    job: 'Design',
    content: '제품 UX/UI 디자인 담당',
    jdUrl: 'https://jogakjogak.com/jd/3',
    memo: '',
    memberId: 103,
    alarmOn: false,
    applyAt: null,
    endedAt: getPastDate(-7),
    createdAt: getPastDate(16),
    updatedAt: getPastDate(15),
    totalPieces: 6,
    completedPieces: 0,
    toDoLists: dummyTodoLists[3],
  },
  {
    jd_id: 3,
    title: 'UX Designer',
    bookmark: true,
    companyName: 'Flow UX Studio',
    job: 'Design',
    content: '사용자 경험 개선을 위한 디자인 업무',
    jdUrl: 'https://jogakjogak.com',
    memo: '',
    memberId: 104,
    alarmOn: true,
    applyAt: null,
    endedAt: getPastDate(-0.5),
    createdAt: getPastDate(14),
    updatedAt: getPastDate(13),
    totalPieces: 6,
    completedPieces: 2,
    toDoLists: dummyTodoLists[4],
  },
  {
    jd_id: 4,
    title: 'Product Manager',
    bookmark: false,
    companyName: 'SprintWave',
    job: 'PM',
    content: '제품 기획 및 로드맵 수립',
    jdUrl: 'https://jogakjogak.com',
    memo: '',
    memberId: 105,
    alarmOn: true,
    applyAt: null,
    endedAt: getPastDate(5),
    createdAt: getPastDate(12),
    updatedAt: getPastDate(11),
    totalPieces: 6,
    completedPieces: 4,
    toDoLists: dummyTodoLists[5],
  },
  {
    jd_id: 5,
    title: 'Visual Designer',
    bookmark: false,
    companyName: 'Canvas Collective',
    job: 'Design',
    content: '브랜드 비주얼 및 그래픽 디자인',
    jdUrl: 'https://jogakjogak.com',
    memo: '',
    memberId: 106,
    alarmOn: false,
    applyAt: getPastDate(3),
    endedAt: getPastDate(2),
    createdAt: getPastDate(10),
    updatedAt: getPastDate(9),
    totalPieces: 6,
    completedPieces: 6,
    toDoLists: dummyTodoLists[6],
  },
];

export const createTourDummySlice: StateCreator<
  TourDummySlice,
  [],
  [],
  TourDummySlice
> = (set) => ({
  dummyJds: dummyJobDescriptions,
  setDummyJds: (dummyJds: JobDescription[]) => set({ dummyJds }),
  updateDummyJd: (jobId: number, updatedFields: Partial<JobDescription>) =>
    set((state) => ({
      dummyJds: state.dummyJds.map((jd) =>
        jd.jd_id === jobId ? { ...jd, ...updatedFields } : jd
      ),
    })),
  dummyJdDetails: dummyJdDetails,
  updateDummyJdDetail: (jobId: number, updatedFields: Partial<JDDetail>) =>
    set((state) => ({
      dummyJdDetails: state.dummyJdDetails.map((jd) =>
        jd.jd_id === jobId ? { ...jd, ...updatedFields } : jd
      ),
    })),
  syncDummyJdAndJdDetail: (jobId: number, updatedFields) =>
    set((state) => ({
      dummyJds: state.dummyJds.map((jd) =>
        jd.jd_id === jobId ? { ...jd, ...updatedFields } : jd
      ),
      dummyJdDetails: state.dummyJdDetails.map((jd) =>
        jd.jd_id === jobId ? { ...jd, ...updatedFields } : jd
      ),
    })),
  dummyCheckedTodoList: [],
  setDummyCheckedTodoList: (checkedTodoList: number[]) =>
    set({ dummyCheckedTodoList: checkedTodoList }),
  addDummyCheckedTodo: (todoId) =>
    set((state) => ({
      dummyCheckedTodoList: state.dummyCheckedTodoList.includes(todoId)
        ? state.dummyCheckedTodoList
        : [...state.dummyCheckedTodoList, todoId],
    })),
  removeDummyCheckedTodo: (todoId: number) =>
    set((state) => ({
      dummyCheckedTodoList: state.dummyCheckedTodoList.filter(
        (id) => id !== todoId
      ),
    })),
});
